- name: Check gradle binary files, if file exists skip
  stat:
    path: "/tmp/gradle-{{ item.version }}-bin.zip"
  register: gradle_tmp_downloaded
  with_items: "{{ gradle_version_with_items }}"
  ignore_errors: True

- name: Download gradle
  shell: wget https://services.gradle.org/distributions/gradle-{{ item.item.version }}-bin.zip -P /tmp
  with_items: "{{ gradle_tmp_downloaded.results }}"
  when: item.stat.exists == False

- name: Check gradle unzip target path, if folder exists skip
  stat:
    path: "/opt/gradle/gradle-{{ item.version }}"
  register: gradle_unzip_target
  with_items: "{{ gradle_version_with_items }}"
  ignore_errors: True

- name: Unzip gradle to /opt/gradle
  shell: unzip -d /opt/gradle /tmp/gradle-{{ item.item.version }}-bin.zip
  with_items: "{{ gradle_unzip_target.results }}"
  when: item.stat.exists == False

- name: Update alternative for gradle
  shell: update-alternatives --install /usr/bin/gradle gradle /opt/gradle/gradle-{{ item.item.version }}/bin/gradle  1081
  with_items: "{{ gradle_unzip_target.results }}"
  when: item.stat.exists == False