---
- name: Add Codium GPG apt Key
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    state: present

- name: Add Codium repository
  apt_repository:
    repo: "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main"
    filename: vscodium.list

- name: Install Codium
  apt:
    name: codium
