---
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'software-properties-common']

- name: download the docker apt key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.gpg.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    filename: docker
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']