---
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install Pyhton 3 alias
  apt:
    name: python-is-python3

- name: Install Pyhton 3 PIP
  apt:
    name: python3-pip

- name: Install python docker extension
  pip:
    name: docker

- name: Install python docker-compose extension
  pip:
    name: docker-compose
